# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [22]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [23]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.02341926 0.07789981 0.24445015 ... 0.24536636 0.21012023 0.18311868]
 [0.73151787 0.92036635 0.32853528 ... 0.02124289 0.40222831 0.98644305]
 [0.27304378 0.01054411 0.53993543 ... 0.65138303 0.6737768  0.90633926]
 ...
 [0.52738142 0.9652171  0.78803416 ... 0.95169614 0.44413395 0.4142004 ]
 [0.64889254 0.35864253 0.20936281 ... 0.78071199 0.36177898 0.68359198]
 [0.48384408 0.96185293 0.891675   ... 0.44918536 0.79410493 0.40502921]]
[[0.92104003 0.80638999 0.66601402 ... 0.23152962 0.88739999 0.40055669]
 [0.80297788 0.75026706 0.73040398 ... 0.01934858 0.80898731 0.60402343]
 [0.56405815 0.92238328 0.39133027 ... 0.00295377 0.23416113 0.11270453]
 ...
 [0.88407712 0.61454197 0.71559521 ... 0.83794854 0.31003987 0.84867029]
 [0.02837763 0.04075472 0.09428414 ... 0.64863763 0.88393527 0.51240959]
 [0.60921084 0.37639054 0.05568954 ... 0.91797762 0.10075658 0.95959118]]


Без использования numpy

In [24]:
def mult(a, b):
    result = [[0 for x in range(len(a))] for y in range(len(b[0]))]
    for i in range(len(a)):
      for j in range(len(b[0])):
        for k in range(len(b)):
          result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [25]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [26]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 547 ms
Wall time: 618 ms


In [27]:
%%time
# засечем время работы функции c NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [28]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3212542171459063e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [29]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.03809665 0.29727113 0.93142351] [0.24541109 0.11082455 0.74285142]


In [30]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [31]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [32]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Значительная часть логики numpy написана на C, поэтому выполнение векторных операций происходит на порядок быстрее.

------------------

### Задание 3
Напишите функцию, которая находит сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [33]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag = np.diag(a)
    even_diag = diag[diag % 2 == 0]
    if len(even_diag) == 0:
        return 0
    return np.sum(even_diag)

In [34]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 1, 7, 5, 1],
       [8, 6, 8, 2, 5],
       [5, 5, 4, 9, 2],
       [6, 3, 1, 6, 1],
       [8, 7, 3, 1, 6]])

In [35]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


22

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [36]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumsum = np.cumsum(X, axis=1)
    row_indices = np.arange(1, X.shape[1] + 1)
    result = cumsum / row_indices[:, np.newaxis]
    return result

In [37]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.16190557 0.35180993 0.18342312 0.59119058 0.49086384 0.75893762
 0.89119822 0.34193614 0.01090782 0.89716134 0.25742135 0.73580774
 0.24193707 0.52533398 0.95606094 0.10535811 0.68029802 0.24797923
 0.64740232 0.45096339 0.72406481 0.71593391 0.4006144  0.40920677
 0.39215735 0.00310335 0.14912598 0.14319134 0.8292508  0.83406955
 0.03933431 0.74715576 0.40036001 0.01331245 0.39025974 0.33427297
 0.56769963 0.75046533 0.68104575 0.79186326 0.28650574 0.8054927
 0.36306976 0.0019026  0.40795971 0.63808128 0.46622789 0.31970962
 0.41702561 0.10559931 0.40832757 0.44456364 0.10269615 0.71924324
 0.22229951 0.48290865 0.79211598 0.4813157  0.09123516 0.89308071
 0.58043555 0.37423709 0.8418045  0.33811855 0.28552737 0.31310315
 0.36113134 0.2920674  0.00367925 0.74527426 0.036959   0.9837519
 0.93603118 0.34011153 0.36913938 0.56167929 0.98159398 0.26726411
 0.39024672 0.4170421  0.33408982 0.27225126 0.08532115 0.5131645
 0.60680981 0.43771625 0.84146752 0.06089766 0.93618604 0.4503773

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [38]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = []
    count = 1
    for i in range(1, len(a)):
        if a[i] == a[i-1]:
            count += 1
        else:
            result.append(a[i-1])
            result.append(count)
            count = 1
    result.append(a[-1])
    result.append(count)

    return np.array(result[0::2]), np.array(result[1::2])

In [39]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(x,num)

CPU times: total: 0 ns
Wall time: 0 ns
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [40]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    X_copy = np.copy(X)
    X_copy[1::2] = a
    X_copy[::2] = np.power(X_copy[::2], 3)
    result = np.concatenate((X, X_copy[::-1]))
    return result

In [41]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(S2)

CPU times: total: 0 ns
Wall time: 1.01 ms
[  1   3   5   7   9 729   5 125   5   1]
